---
# Default values for monitoring role

# Node Exporter settings
node_exporter_version: "1.5.0"
node_exporter_arch: "{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}"
node_exporter_web_listen_address: "127.0.0.1:9100"
node_exporter_enabled_collectors:
  - cpu
  - diskstats
  - filesystem
  - loadavg
  - meminfo
  - netstat
  - textfile
  - time
  - uname
