---
# Monitoring role tasks

- name: Create node_exporter system group
  group:
    name: node_exporter
    state: present
    system: yes

- name: Create node_exporter system user
  user:
    name: node_exporter
    groups: node_exporter
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    mode: 0644

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy node_exporter binary to /usr/local/bin
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: 0755
    remote_src: yes

- name: Create node_exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Create textfile collector directory
  file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: 0755

- name: Enable and start node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes

- name: Allow node_exporter port in UFW
  ufw:
    rule: allow
    port: "9100"
    proto: tcp
    from_ip: "127.0.0.1"
  notify: reload ufw
  when: firewall_allowed_tcp_ports is defined
