---
# Default values for kamal role

# Deployment user configuration
deploy_user: "{{ ansible_user }}"
deploy_user_home: "/home/{{ deploy_user }}"
deploy_apps_dir: "{{ deploy_user_home }}/apps"

# System tuning parameters for optimized container performance
sysctl_config:
  net.ipv4.tcp_fin_timeout: 15
  net.ipv4.tcp_tw_reuse: 1
  net.core.somaxconn: 65536
  net.ipv4.ip_local_port_range: "1024 65535"
  net.ipv4.tcp_max_syn_backlog: 65536
  vm.overcommit_memory: 1
  vm.swappiness: 10
  fs.file-max: 2097152

# Swap configuration
configure_swap: true
swap_file_path: "/swapfile"
swap_size_mb: 2048
