# roles/kamal/defaults/main.yml - Updated with dedicated user
---
# Kamal deployment user configuration
kamal_user: "kamal"
kamal_user_home: "/home/{{ kamal_user }}"
kamal_apps_dir: "{{ kamal_user_home }}/apps"

# Kamal CLI installation
install_kamal_cli: true
kamal_version: "2.0.0" # Set to 'latest' for latest version

# Create example configuration files
create_kamal_example: true

# System tuning parameters for optimized container performance
sysctl_config:
  net.ipv4.tcp_fin_timeout: 15
  net.ipv4.tcp_tw_reuse: 1
  net.core.somaxconn: 65536
  net.ipv4.ip_local_port_range: "1024 65535"
  net.ipv4.tcp_max_syn_backlog: 65536
  vm.overcommit_memory: 1
  vm.swappiness: 10
  fs.file-max: 2097152

# Swap configuration
configure_swap: true
swap_file_path: "/swapfile"
swap_size_mb: 2048

# Docker user configuration (will add kamal user to docker group)
docker_users:
  - "{{ kamal_user }}"
