---
# Common role handlers

- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
