---
# Common role tasks

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
  when: security_autoupdate_enabled | bool

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set locale
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Ensure sudo is installed
  apt:
    name: sudo
    state: present

- name: Configure fail2ban
  block:
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Create fail2ban configuration
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 5

          [sshd]
          enabled = true

    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
        enabled: yes
  when: security_fail2ban_enabled | bool

- name: Setup automatic security updates
  block:
    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades
      template:
        src: 20auto-upgrades.j2
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: 0644

    - name: Configure unattended-upgrades options
      template:
        src: 50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: 0644
