# roles/kamal/tasks/main.yml - Versão melhorada com usuário dedicado
---
# Kamal role tasks with dedicated user

- name: Create dedicated kamal group
  group:
    name: "{{ kamal_user }}"
    state: present
    system: yes

- name: Create dedicated kamal user
  user:
    name: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    groups: docker
    shell: /bin/bash
    home: "{{ kamal_user_home }}"
    create_home: yes
    system: no
    comment: "Kamal deployment user"
    password_lock: yes # Disable password login, SSH key only
  register: kamal_user_created

- name: Set proper ownership for kamal user home directory
  file:
    path: "{{ kamal_user_home }}"
    owner: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    mode: "0755"
    state: directory

- name: Create .ssh directory for kamal user
  file:
    path: "{{ kamal_user_home }}/.ssh"
    state: directory
    owner: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    mode: "0700"

- name: Configure SSH keys for kamal user
  authorized_key:
    user: "{{ kamal_user }}"
    state: present
    key: "{{ lookup('file', 'files/ssh_keys/deploy_key.pub') }}"
    comment: "Kamal deployment key"
    key_options: "no-port-forwarding,no-X11-forwarding,no-agent-forwarding"
  when: lookup('file', 'files/ssh_keys/deploy_key.pub', errors='ignore')

- name: Create SSH config file for kamal user
  file:
    path: "{{ kamal_user_home }}/.ssh/config"
    state: touch
    owner: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    mode: "0600"
    modification_time: preserve
    access_time: preserve

- name: Create applications directory
  file:
    path: "{{ kamal_apps_dir }}"
    state: directory
    owner: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    mode: "0755"

- name: Create kamal configuration directory
  file:
    path: "{{ kamal_user_home }}/.kamal"
    state: directory
    owner: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    mode: "0755"

- name: Create kamal logs directory
  file:
    path: "{{ kamal_user_home }}/logs"
    state: directory
    owner: "{{ kamal_user }}"
    group: "{{ kamal_user }}"
    mode: "0755"

- name: Configure sudo access for kamal user (minimal permissions)
  template:
    src: kamal-sudo.j2
    dest: /etc/sudoers.d/kamal-deploy
    mode: "0440"
    owner: root
    group: root
    validate: "visudo -cf %s"

# System tuning for optimal container performance
- name: Set kernel parameters for optimal Docker performance
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_dict: "{{ sysctl_config }}"

# Configure swap
- name: Configure swap
  block:
    - name: Check if swap file exists
      stat:
        path: "{{ swap_file_path }}"
      register: swap_file_check

    - name: Create swap file
      command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_size_mb }}
      when: not swap_file_check.stat.exists

    - name: Set swap file permissions
      file:
        path: "{{ swap_file_path }}"
        mode: "0600"
      when: not swap_file_check.stat.exists

    - name: Format swap file
      command: mkswap {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Enable swap
      command: swapon {{ swap_file_path }}
      when: not swap_file_check.stat.exists

    - name: Add swap to fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ swap_file_path }} none swap sw 0 0"
        state: present
      when: not swap_file_check.stat.exists
  when: configure_swap | bool

- name: Display kamal user setup information
  debug:
    msg:
      - "Kamal deployment user created: {{ kamal_user }}"
      - "Applications directory: {{ kamal_apps_dir }}"
      - "SSH into server as: ssh {{ kamal_user }}@{{ ansible_host }}"
