---
- name: Validate prerequisites
  hosts: all
  tags: prerequisites
  roles:
    - prerequisites

- name: Apply common configuration
  hosts: all
  tags: common
  roles:
    - common

- name: Configure servers for Kamal 2 deployment
  hosts: kamal_servers
  tags: kamal
  roles:
    - docker
    - firewall
    - kamal
    - { role: monitoring, when: monitoring_enabled | default(false) }
